backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow
media_folder: "assets/uploads" # Media files will be stored in the repo under src/assets/images/posts
public_folder: "/assets/uploads" # The src attribute for uploaded media will begin with assets/images/posts

collections:
  - name: "categorias" # Used in routes, e.g., /admin/collections/blog
    label: "Categorias" # Used in the UI
    folder: "src/categorias" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Categoría" }
      - { name: "icono", label: "Icono de Categoría", widget: "image" }
      - { name: "descripcion", label: "Descripción", widget: "markdown" }
  - name: "video" # Used in routes, e.g., /admin/collections/video
    label: "Video" # Used in the UI
    folder: "src/videos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { name: "description", label: "Description" }
      - { name: "link", label: "Enlace de video" }
      - { name: "date", label: "Date", widget: "datetime" }
